-- MySQL Script generated by MySQL Workbench
-- Sat Nov 19 01:31:17 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jmrs
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jmrs` ;

-- -----------------------------------------------------
-- Schema jmrs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jmrs` DEFAULT CHARACTER SET utf8 ;
USE `jmrs` ;

-- -----------------------------------------------------
-- Table `jmrs`.`user_`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jmrs`.`user_` ;

CREATE TABLE IF NOT EXISTS `jmrs`.`user_` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `status` INT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `jmrs`.`user_` (`name` ASC);


-- -----------------------------------------------------
-- Table `jmrs`.`region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jmrs`.`region` ;

CREATE TABLE IF NOT EXISTS `jmrs`.`region` (
  `region_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`region_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jmrs`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jmrs`.`country` ;

CREATE TABLE IF NOT EXISTS `jmrs`.`country` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `region_id` INT NULL,
  PRIMARY KEY (`country_id`),
  CONSTRAINT `country_region_id`
    FOREIGN KEY (`region_id`)
    REFERENCES `jmrs`.`region` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `country_region_id_idx` ON `jmrs`.`country` (`region_id` ASC);


-- -----------------------------------------------------
-- Table `jmrs`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jmrs`.`room` ;

CREATE TABLE IF NOT EXISTS `jmrs`.`room` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `comment` VARCHAR(300) NULL,
  `region_id` INT NULL,
  `country_id` INT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`room_id`),
  CONSTRAINT `room_region_id`
    FOREIGN KEY (`region_id`)
    REFERENCES `jmrs`.`region` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `room_country_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `jmrs`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `room_region_id_idx` ON `jmrs`.`room` (`region_id` ASC);

CREATE INDEX `room_country_id_idx` ON `jmrs`.`room` (`country_id` ASC);


-- -----------------------------------------------------
-- Table `jmrs`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jmrs`.`book` ;

CREATE TABLE IF NOT EXISTS `jmrs`.`book` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `book_user_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `name` VARCHAR(200) NULL,
  `comment` VARCHAR(1000) NULL,
  PRIMARY KEY (`book_id`),
  CONSTRAINT `book_user_id`
    FOREIGN KEY (`book_user_id`)
    REFERENCES `jmrs`.`user_` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `book_room_id`
    FOREIGN KEY (`room_id`)
    REFERENCES `jmrs`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `book_user_id_idx` ON `jmrs`.`book` (`book_user_id` ASC);

CREATE INDEX `book_room_id_idx` ON `jmrs`.`book` (`room_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `jmrs`.`user_`
-- -----------------------------------------------------
START TRANSACTION;
USE `jmrs`;
INSERT INTO `jmrs`.`user_` (`user_id`, `name`, `password`, `role`, `status`) VALUES (1, 'guest', 'guest', 'GUEST', 1);
INSERT INTO `jmrs`.`user_` (`user_id`, `name`, `password`, `role`, `status`) VALUES (2, 'user', 'user', 'USER', 1);
INSERT INTO `jmrs`.`user_` (`user_id`, `name`, `password`, `role`, `status`) VALUES (3, 'admin', 'admin', 'ADMIN', 1);

COMMIT;

